Example Updates - updated sdr and sdr2msghub structure. Added cross-compiling. Documentation updated (README and api description). sdr/bbcfake now working. Moved sdr to port 80. Made changes to exchangePublishScript, added full path to services in blessedSamples

diff --git a/edge/msghub/sdr2msghub/Makefile b/edge/msghub/sdr2msghub/Makefile
--- a/edge/msghub/sdr2msghub/Makefile
+++ b/edge/msghub/sdr2msghub/Makefile
@@ -1,62 +1,101 @@
-# Transform the machine arch into some standard values: "arm", "arm64", or "amd64"
-SYSTEM_ARCH := $(shell uname -m | sed -e 's/aarch64.*/arm64/' -e 's/x86_64.*/amd64/' -e 's/armv.*/arm/')
+# Make targets for building the IBM sample sdr2msghub edge service
 
-# To build for an arch different from the current system, set this env var to 1 of the values in the comment above
-export ARCH ?= $(SYSTEM_ARCH)
+# This imports the variables from horizon/hzn.json. You can ignore these lines, but do not remove them.
+-include horizon/.hzn.json.tmp.mk
 
-# Container image version and workload name
-export SDR2MSGHUB_VERSION = 0.0.4
-export SDR2MSGHUB_NAME = sdr2msghub
+# Default ARCH to the architecture of this machines (as horizon/golang describes it). Can be overridden.
+export ARCH ?= $(shell hzn architecture)
 
-# When creating the service definition, we reference these
-export SDR_NAME ?= sdr
-export SDR_VERSION ?= 0.0.7
-export GPS_NAME ?= gps
-export GPS_VERSION ?= 2.0.5
+# Build the docker image for the current architecture
+build: main.go
+ifeq (,$(findstring amd64,$(ARCH)))
+	mkdir -p tmp/$(ARCH)
+	cp ../../../tools/kafkacat/$(ARCH)/*.rsa.pub ../../../tools/kafkacat/$(ARCH)/kafkacat-*.apk tmp/$(ARCH)
+endif
+	docker build -t $(DOCKER_IMAGE_BASE)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) ../../
+ifeq (,$(findstring amd64,$(ARCH)))
+	rm -f tmp/$(ARCH)/*.rsa.pub tmp/$(ARCH)/kafkacat-*.apk
+endif
 
-# Construct our Docker registry path and other architecture-dependent values
-DOCKER_NAME ?= $(ARCH)_$(SDR2MSGHUB_NAME)
-export DOCKER_HUB_ID ?= openhorizon
-IMAGE_PATH = $(DOCKER_HUB_ID)/$(DOCKER_NAME):$(SDR2MSGHUB_VERSION)
+# Build the docker image for 3 architectures
+build-all-arches:
+	ARCH=amd64 $(MAKE) build
+	ARCH=arm $(MAKE) build
+	ARCH=arm64 $(MAKE) build
 
-export MYDOMAIN ?= github.com.open-horizon.examples
-MSGHUB_TOPIC ?= sdr-audio
+# Soon we can use 'hzn service log ...' for all platforms
+ifeq ($(shell uname -s),Darwin)
+GET_SVC_OUTPUT = docker logs `docker ps -q --filter name=sdr2msghub`
+else
+GET_SVC_OUTPUT = $(SYSLOG_SUDO) grep sdr2msghub[[] /var/log/syslog
+endif
 
-build: target/build_$(ARCH)
+# Run and verify the service
+test: build
+	hzn dev service start -S
+	@echo 'Testing service...'
+	sleep 20  # may have to increase this time depending on the speed of your machine
+	@if $(GET_SVC_OUTPUT) | grep 'found new station:'; then \
+	  hzn dev service stop; \
+	  echo 'Service test succeeded.'; \
+	else \
+	  hzn dev service stop; \
+	  echo 'Service test failed!'; \
+	  false; \
+	fi
 
-target/build_$(ARCH): main.go
-	docker build -t $(IMAGE_PATH) -f Dockerfile.$(ARCH) ../../
-	touch target/build_$(ARCH)
+# Publish the service to the Horizon Exchange for the current architecture
+publish-service:
+	hzn exchange service publish -f horizon/service.definition.json
 
-run: target/build_$(ARCH)
-	-docker network create sdr
-	#-docker rm -f $(IMAGE_PATH)
-	docker run -it --rm -e HZN_ORGANIZATION="$(HZN_ORG_ID)" -e USE_GPS="false" -e HZN_DEVICE_ID="$(HZN_DEVICE_ID)" -e MSGHUB_API_KEY="$(MSGHUB_API_KEY)" -e MSGHUB_BROKER_URL="$(MSGHUB_BROKER_URL)" -e MSGHUB_TOPIC="$(MSGHUB_TOPIC)" --name $(SDR2MSGHUB_NAME) --net=sdr --net-alias=$(SDR2MSGHUB_NAME) $(IMAGE_PATH)
+# Build, run and verify, if test succeeds then publish (for the current architecture)
+build-test-publish: build test publish-service
 
-# To publish you must have write access to the docker hub openhorizon user
-publish: target/build_$(ARCH)
-	docker push $(IMAGE_PATH)
+# Build/test/publish the service to the Horizon Exchange for 3 architectures and publish a deployment pattern for those architectures
+publish-all-arches:
+	ARCH=amd64 $(MAKE) build-test-publish
+	ARCH=arm $(MAKE) build-test-publish
+	ARCH=arm64 $(MAKE) build-test-publish
+	hzn exchange pattern publish -f horizon/pattern-all-arches.json
 
-# Create/update the metadata in the exchange for this service. This also pushes the image to docker hub.
-publish-service: #todo: add this: target/build_$(ARCH)
-	: $${HZN_ORG_ID:?} $${HZN_EXCHANGE_USER_AUTH:?} $${PRIVATE_KEY_FILE:?} $${PUBLIC_KEY_FILE:?} $${MSGHUB_BROKER_URL:?}   # this verifies these env vars are set
-	hzn exchange service publish -k $$PRIVATE_KEY_FILE -K $$PUBLIC_KEY_FILE -f horizon/service.definition.json
+# target for script - overwrite and pull insitead of push docker image
+publish-service-overwrite:
+	hzn exchange service publish -O -P -f horizon/service.definition.json
 
-# Create/update the deployment pattern for a set of edge nodes
-publish-pattern:
-	: $${HZN_ORG_ID:?} $${HZN_EXCHANGE_USER_AUTH:?}   # this verifies these env vars are set
-	hzn exchange pattern publish -p $$SDR2MSGHUB_NAME -f horizon/pattern/sdr2msghub.json
+# new target for new exchange to run on startup to publish only
+publish-only:
+	ARCH=amd64 $(MAKE) publish-service-overwrite
+	ARCH=arm $(MAKE) publish-service-overwrite
+	ARCH=arm64 $(MAKE) publish-service-overwrite
+	hzn exchange pattern publish -f horizon/pattern-all-arches.json
+
+# Create a topic in msg hub for cpu2msghub to send data to
+MSGHUB_TOPIC ?= sdr2msghub
+msghub-topic:
+	: $${MSGHUB_API_KEY:?} $${MSGHUB_ADMIN_URL:?}
+	curl -sS -w %{http_code} -H 'Content-Type: application/json' -H "X-Auth-Token: $$MSGHUB_API_KEY" -d "{ \"name\": \"$(MSGHUB_TOPIC)\", \"partitions\": 2 }" $$MSGHUB_ADMIN_URL/admin/topics
+
+# List the topics currently in msg hub
+msghub-topic-list:
+	@: $${MSGHUB_API_KEY:?} $${MSGHUB_ADMIN_URL:?}
+	@curl -sS -H "X-Auth-Token: $$MSGHUB_API_KEY" $$MSGHUB_ADMIN_URL/admin/topics | jq -r ".[] | .name"
+
+clean:
+	-docker rmi $(DOCKER_IMAGE_BASE)_$(ARCH):$(SERVICE_VERSION) 2> /dev/null || :
+
+clean-all-archs:
+	ARCH=amd64 $(MAKE) clean
+	ARCH=arm $(MAKE) clean
+	ARCH=arm64 $(MAKE) clean
+
+
 
 fakepub: fake/main.go
 	go build -o $@ $<
 
-clean:
-	-docker rm -f $(IMAGE_PATH)
-	-docker stop $(SDR2MSGHUB_NAME) && docker rm $(SDR2MSGHUB_NAME)
-	-docker rmi $(SDR2MSGHUB_NAME)
-	-docker network rm example
-	-rm target/*
-	-rm -f fakepub
+# This imports the variables from horizon/hzn.cfg. You can ignore these lines, but do not remove them.
+horizon/.hzn.json.tmp.mk: horizon/hzn.json
+	@ hzn util configconv -f $< > $@
 
 .PHONY: default all build dev run check publish publish-service publish-pattern fakepub clean
 
diff --git a/edge/services/sdr/Makefile b/edge/services/sdr/Makefile
--- a/edge/services/sdr/Makefile
+++ b/edge/services/sdr/Makefile
@@ -1,46 +1,67 @@
-# Transform the machine arch into some standard values: "arm", "arm64", or "amd64"
-SYSTEM_ARCH := $(shell uname -m | sed -e 's/aarch64.*/arm64/' -e 's/x86_64.*/amd64/' -e 's/armv.*/arm/')
 
-# To build for an arch different from the current system, set this env var to 1 of the values in the comment above
-export ARCH ?= $(SYSTEM_ARCH)
+-include horizon/.hzn.json.tmp.mk
 
-export SDR_VERSION = 0.0.7
-export SDR_NAME = sdr
+# Default ARCH to the architecture of this machines (as horizon/golang describes it)
+export ARCH ?= $(shell hzn architecture)
 
-# These variables can be overridden from the environment
-DOCKER_NAME ?= $(ARCH)_$(SDR_NAME)
-export DOCKER_HUB_ID ?= openhorizon
-export MYDOMAIN ?= github.com.open-horizon.examples
+build:
+	docker build -t $(DOCKER_IMAGE_BASE)_$(ARCH):$(SERVICE_VERSION) -f ./Dockerfile.$(ARCH) .
 
-default: build
+build-all-arches:
+	ARCH=amd64 $(MAKE) build
+	ARCH=arm $(MAKE) build
+	ARCH=arm64 $(MAKE) build
 
-all: build run
+# Soon we can use 'hzn service log ...' for all platforms
+ifeq ($(shell uname -s),Darwin)
+GET_SVC_OUTPUT = docker logs `docker ps -q --filter name=sdr`
+else
+GET_SVC_OUTPUT = $(SYSLOG_SUDO) grep sdr /var/log/syslog
+endif
 
+run:
+	docker run -it --rm --privileged $(DOCKER_IMAGE_BASE)_$(ARCH):$(SERVICE_VERSION)
 
-build: target/build_$(ARCH)
+test: build
+	hzn dev service start -S
+	@echo 'Testing service...'
+	sleep 1
+	@if $(GET_SVC_OUTPUT) | grep 'starting rtl_rpcd'; then \
+		hzn dev service stop; \
+		echo 'Service test succeeded.'; \
+	else \
+		hzn dev service stop; \
+		echo 'Service test failed!'; \
+		false; \
+	fi
 
-target/build_$(ARCH): Dockerfile.$(ARCH) main.go
-	docker build -t $(DOCKER_HUB_ID)/$(DOCKER_NAME):$(SDR_VERSION) -f Dockerfile.$(ARCH) --build-arg version=$(SDR_VERSION) .
-	touch target/build_$(ARCH)
+# Create/update the metadata in the exchange for this service
+publish-service:
+	hzn exchange service publish -f horizon/service.definition.json
 
-run: target/build_$(ARCH)
-	-docker network create sdr
-	-docker kill $(SDR_NAME)
-	docker run -it --rm --privileged --name $(SDR_NAME) --net=sdr --net-alias=rtlsdr --publish=5427:5427 $(DOCKER_HUB_ID)/$(DOCKER_NAME):$(SDR_VERSION)
+build-test-publish: build test publish-service
 
-# To publish you must have write access to the docker hub openhorizon user
-publish: target/build_$(ARCH)
-	docker push $(DOCKER_HUB_ID)/$(DOCKER_NAME):$(SDR_VERSION)
+publish-all-arches:
+	ARCH=amd64 $(MAKE) build-test-publish
+	ARCH=arm $(MAKE) build-test-publish
+	ARCH=arm64 $(MAKE) build-test-publish
 
-# Create/update the metadata in the exchange for this service. This also pushes the image to docker hub.
-publish-service: #todo: add this: target/build_$(ARCH)
-	: $${HZN_ORG_ID:?} $${HZN_EXCHANGE_USER_AUTH:?} $${PRIVATE_KEY_FILE:?} $${PUBLIC_KEY_FILE:?}   # this verifies these env vars are set
-	hzn exchange service publish -k $$PRIVATE_KEY_FILE -K $$PUBLIC_KEY_FILE -f horizon/service.definition.json
+# new target for icp exchange to run on startup to publish only
+publish-only:
+	ARCH=amd64 $(MAKE) publish-service
+	ARCH=arm $(MAKE) publish-service
+	ARCH=arm64 $(MAKE) publish-service
 
 clean:
-	rm target/*
-	-docker rm -f $(DOCKER_HUB_ID)/$(DOCKER_NAME):$(SDR_VERSION)
-	-docker rmi cpu
-	-docker network rm example
+	-docker rmi $(DOCKER_IMAGE_BASE)_$(ARCH):$(SERVICE_VERSION) 2> /dev/null || :
+
+clean-all-arches:
+	ARCH=amd64 $(MAKE) clean
+	ARCH=arm $(MAKE) clean
+	ARCH=arm64 $(MAKE) clean
+
+# This imports the variables from horizon/hzn.cfg. You can ignore these lines, but do not remove them.
+horizon/.hzn.json.tmp.mk: horizon/hzn.json
+	@ hzn util configconv -f $< > $@
 
 .PHONY: default all build dev run check publish publish-service clean
